// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/ocp-calendar-api/ocp-calendar-api.proto

package ocp_calendar_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on CreateCalendarRequestV1 with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateCalendarRequestV1) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Type

	// no validation rules for Link

	return nil
}

// CreateCalendarRequestV1ValidationError is the validation error returned by
// CreateCalendarRequestV1.Validate if the designated constraints aren't met.
type CreateCalendarRequestV1ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCalendarRequestV1ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCalendarRequestV1ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCalendarRequestV1ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCalendarRequestV1ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCalendarRequestV1ValidationError) ErrorName() string {
	return "CreateCalendarRequestV1ValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCalendarRequestV1ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCalendarRequestV1.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCalendarRequestV1ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCalendarRequestV1ValidationError{}

// Validate checks the field values on DescribeCalendarRequestV1 with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeCalendarRequestV1) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// DescribeCalendarRequestV1ValidationError is the validation error returned by
// DescribeCalendarRequestV1.Validate if the designated constraints aren't met.
type DescribeCalendarRequestV1ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeCalendarRequestV1ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeCalendarRequestV1ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeCalendarRequestV1ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeCalendarRequestV1ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeCalendarRequestV1ValidationError) ErrorName() string {
	return "DescribeCalendarRequestV1ValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeCalendarRequestV1ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeCalendarRequestV1.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeCalendarRequestV1ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeCalendarRequestV1ValidationError{}

// Validate checks the field values on ListCalendarRequestV1 with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListCalendarRequestV1) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Limit

	// no validation rules for Offset

	// no validation rules for UserId

	// no validation rules for Type

	return nil
}

// ListCalendarRequestV1ValidationError is the validation error returned by
// ListCalendarRequestV1.Validate if the designated constraints aren't met.
type ListCalendarRequestV1ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCalendarRequestV1ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCalendarRequestV1ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCalendarRequestV1ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCalendarRequestV1ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCalendarRequestV1ValidationError) ErrorName() string {
	return "ListCalendarRequestV1ValidationError"
}

// Error satisfies the builtin error interface
func (e ListCalendarRequestV1ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCalendarRequestV1.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCalendarRequestV1ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCalendarRequestV1ValidationError{}

// Validate checks the field values on RemoveCalendarRequestV1 with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveCalendarRequestV1) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// RemoveCalendarRequestV1ValidationError is the validation error returned by
// RemoveCalendarRequestV1.Validate if the designated constraints aren't met.
type RemoveCalendarRequestV1ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveCalendarRequestV1ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveCalendarRequestV1ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveCalendarRequestV1ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveCalendarRequestV1ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveCalendarRequestV1ValidationError) ErrorName() string {
	return "RemoveCalendarRequestV1ValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveCalendarRequestV1ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveCalendarRequestV1.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveCalendarRequestV1ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveCalendarRequestV1ValidationError{}
